//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication14
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public int A_Id { get; set; }
        public string Answer { get; set; }
        public int Q_Id { get; set; }
        public Nullable<int> Next_Question { get; set; }
        public string Last_Text { get; set; }
    
        public virtual Questions Questions { get; set; }
    }
}
