//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication14
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRegesteration
    {
        public string FristName { get; set; }
        public string LastName { get; set; }
        public int UserID { get; set; }
        public string Email { get; set; }
        public string Passwrd { get; set; }
    }
}
